apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/NAS/all_nodes/kubernetes/container_data/wiki"