apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/NASSD/kubernetes/data/ombi/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ombi-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ombi
  name: ombi
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: ombi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ombi
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          image: lscr.io/linuxserver/ombi
          name: ombi
          ports:
            - containerPort: 3579
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: ombi-pv-claim
      volumes:
        - name: ombi-pv-claim
          persistentVolumeClaim:
            claimName: ombi-pv-claim
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ombi
  name: ombi
spec:
  type: LoadBalancer
  ports:
  - name: "3579"
    port: 3579
    protocol: TCP
    targetPort: 3579
  selector:
    io.kompose.service: ombi
  sessionAffinity: None
