apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/NASSD/kubernetes/data/blog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: blog
  name: blog
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: blog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: blog
    spec:
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: "192.168.50.2:3306"
            - name: WORDPRESS_DB_USER
              value: "Wordpress"
            - name: WORDPRESS_DB_PASSWORD
              value: uqKmRvr3JoyTrxzyJ6fY
            - name: WORDPRESS_DB_NAME
              value: blog
          image: wordpress
          name: blog
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www/html"
              name: blog-pv-storage
          resources: {}
      volumes:
        - name: blog-pv-storage
          persistentVolumeClaim:
            claimName: blog-pv-claim
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: blog
  name: blog
spec:
  type: LoadBalancer
  ports:
  - name: "8000"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: blog
  sessionAffinity: None
