version: '3.1'

services:

  wordpress:
    image: wordpress
    name: blog
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: 192.168.50.100:3306
      WORDPRESS_DB_USER: Wordpress
      WORDPRESS_DB_PASSWORD: PASSWORD
      WORDPRESS_DB_NAME: blog
    volumes:
      - wordpress:/var/www/html