version: "2.1"
services:
  calibre:
    image: lscr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - /mnt/HDD/shared/calibre/data/:/config
      - /mnt/HDD/shared/calibre/library:/books
    ports:
      - 8083:8080
      - 8084:8081
    restart: unless-stopped
