apiVersion: v1
kind: PersistentVolume
metadata:
  name: nitter-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/NASSD/kubernetes/data/nitter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nitter-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: nitter
  name: nitter
spec:
  replicas: 4
  selector:
    matchLabels:
      io.kompose.service: nitter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nitter
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
          image: zedeus/nitter:latest
          name: nitter
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/src"
              name: nitter-pv-storage
          resources: {}
      volumes:
        - name: nitter-pv-storage
          persistentVolumeClaim:
            claimName: nitter-pv-claim
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nitter
  name: nitter
spec:
  type: LoadBalancer
  ports:
  - name: "9090"
    port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: nitter
  sessionAffinity: None
